dist: xenial
language: python
python: 3.7

install:
  - pip install kodi-addon-checker

before_script:
- rm -R .*
- rm *.yml
- rm CODE_OF_CONDUCT.md
- rm PULL_REQUEST_TEMPLATE.md
- rm changelog.md
- rm test.py
- git config core.quotepath false

# command to run our tests
script:
  - kodi-addon-checker --branch=leia $([ "$TRAVIS_PULL_REQUEST" != "false" ] && echo --PR $(git diff --diff-filter=d --name-only HEAD~ | grep / | cut -d / -f1 | sort | uniq))
