# This is a basic workflow to help you get started with Actions

name: Update operator list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-op-list-wiki:
    runs-on: ubuntu-latest

    name: Update Wiki operator list
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        yes | pip install requests
    - name: Get hGo Wiki
      run: git clone https://github.com/arvvoid/plugin.video.hbogoeu.wiki.git ../hgowiki
    - name: Generate Operators list
      run: python gen_operator_list.py
    - name: Update Wiki
      run: |
        cd ../hgowiki
        git config user.email "${{secrets.EMAIL}}"
        git config user.name "${{ github.actor }}"
        git add .
        git commit -m "Auto-update operators list"
        git push
